### ISSUE TITLE
KeyError: 'commit_message'

### ISSUE THREAD

**Issue by madhead** [ansible-collections/community.grafana#153]
##### SUMMARY
`KeyError: 'commit_message'` appears in `community.grafana.grafana_dashboard` when I'm trying to update a dashboard in Grafana Cloud.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
- `community.grafana.grafana_dashboard`

##### ANSIBLE VERSION
```
ansible 2.10.5
  config file = /home/madhead/Projects/ImgMacroBot/deploy/ansible.cfg
  configured module search path = ['/home/madhead/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  executable location = /bin/ansible
  python version = 3.9.1 (default, Dec 13 2020, 11:55:53) [GCC 10.2.0]
```

##### CONFIGURATION

```
ANSIBLE_NOCOWS(/home/madhead/Projects/ImgMacroBot/deploy/ansible.cfg) = True
INVENTORY_ENABLED(/home/madhead/Projects/ImgMacroBot/deploy/ansible.cfg) = ['oracle.oci.oci']
```

###### Target machine
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
```

###### Host
```
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=20.2.1
DISTRIB_CODENAME=Nibia
DISTRIB_DESCRIPTION="Manjaro Linux"
```

###### Collections & Roles from the Galaxy
```
Starting galaxy role install process
- changing role geerlingguy.java from 1.10.0 to unspecified
- downloading role 'java', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-java/archive/1.10.0.tar.gz
- extracting geerlingguy.java to /home/madhead/.ansible/roles/geerlingguy.java
- geerlingguy.java (1.10.0) was installed successfully
Starting galaxy collection install process
Process install dependency map
Starting collection install process
Installing 'community.crypto:1.4.0' to '/home/madhead/.ansible/collections/ansible_collections/community/crypto'
Downloading https://galaxy.ansible.com/download/community-crypto-1.4.0.tar.gz to /home/madhead/.ansible/tmp/ansible-local-58818tv_2tyuu/tmpgecb0ovu
community.crypto (1.4.0) was installed successfully
Installing 'community.grafana:1.2.0' to '/home/madhead/.ansible/collections/ansible_collections/community/grafana'
Downloading https://galaxy.ansible.com/download/community-grafana-1.2.0.tar.gz to /home/madhead/.ansible/tmp/ansible-local-58818tv_2tyuu/tmpgecb0ovu
community.grafana (1.2.0) was installed successfully
Installing 'nginxinc.nginx_core:0.3.0' to '/home/madhead/.ansible/collections/ansible_collections/nginxinc/nginx_core'
Downloading https://galaxy.ansible.com/download/nginxinc-nginx_core-0.3.0.tar.gz to /home/madhead/.ansible/tmp/ansible-local-58818tv_2tyuu/tmpgecb0ovu
nginxinc.nginx_core (0.3.0) was installed successfully
Installing 'oracle.oci:2.15.0' to '/home/madhead/.ansible/collections/ansible_collections/oracle/oci'
Downloading https://galaxy.ansible.com/download/oracle-oci-2.15.0.tar.gz to /home/madhead/.ansible/tmp/ansible-local-58818tv_2tyuu/tmpgecb0ovu
oracle.oci (2.15.0) was installed successfully
```

##### STEPS TO REPRODUCE

The role I'm trying to apply for my target host is on GitHub: https://github.com/madhead/ImgMacroBot/blob/issues/10/deploy/roles/imgmacrobot/tasks/grafana.yml

I'm running it like `./ImgMacroBot.yml -i inventory.oci.yml --tag grafana` with all the environment variables and values available.

##### EXPECTED RESULTS
The dashboard is created or updated with the failing task (see below) reporting "ok" or "changed", but not failing

##### ACTUAL RESULTS
The ["Ensure overview dashboard exists"](https://github.com/madhead/ImgMacroBot/blob/9a1cdf4ca843034d2428f0052c10b4958cacdc9a/deploy/roles/imgmacrobot/tasks/grafana.yml#L14) task fails:

```
TASK [imgmacrobot : Ensure overview dashboard exists] ***************************************************************************************************************************************
task path: /home/madhead/Projects/ImgMacroBot/deploy/roles/imgmacrobot/tasks/grafana.yml:14
<129.213.115.167> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<129.213.115.167> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/home/madhead/.ssh/bots@oracle-cloud"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ubuntu"' -o ConnectTimeout=10 -o ControlPath=/home/madhead/.ansible/cp/ce66bf9464 129.213.115.167 '/bin/sh -c '"'"'echo ~ubuntu && sleep 0'"'"''                                                                                                                                        
<129.213.115.167> (0, b'/home/ubuntu\n', b'')
<129.213.115.167> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<129.213.115.167> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/home/madhead/.ssh/bots@oracle-cloud"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ubuntu"' -o ConnectTimeout=10 -o ControlPath=/home/madhead/.ansible/cp/ce66bf9464 129.213.115.167 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/ubuntu/.ansible/tmp `"&& mkdir "` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1614010640.9152727-57712-172306848124621 `" && echo ansible-tmp-1614010640.9152727-57712-172306848124621="` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1614010640.9152727-57712-172306848124621 `" ) && sleep 0'"'"''                           
<129.213.115.167> (0, b'ansible-tmp-1614010640.9152727-57712-172306848124621=/home/ubuntu/.ansible/tmp/ansible-tmp-1614010640.9152727-57712-172306848124621\n', b'')
Using module file /home/madhead/.ansible/collections/ansible_collections/community/grafana/plugins/modules/grafana_dashboard.py
<129.213.115.167> PUT /home/madhead/.ansible/tmp/ansible-local-57589z2k_46lp/tmp0iah8m_b TO /home/ubuntu/.ansible/tmp/ansible-tmp-1614010640.9152727-57712-172306848124621/AnsiballZ_grafana_dashboard.py                                                                                                                                                                                 
<129.213.115.167> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/home/madhead/.ssh/bots@oracle-cloud"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ubuntu"' -o ConnectTimeout=10 -o ControlPath=/home/madhead/.ansible/cp/ce66bf9464 '[129.213.115.167]'                                                                                                                                                                             
<129.213.115.167> (0, b'sftp> put /home/madhead/.ansible/tmp/ansible-local-57589z2k_46lp/tmp0iah8m_b /home/ubuntu/.ansible/tmp/ansible-tmp-1614010640.9152727-57712-172306848124621/AnsiballZ_grafana_dashboard.py\n', b'')                                                                                                                                                               
<129.213.115.167> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<129.213.115.167> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/home/madhead/.ssh/bots@oracle-cloud"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ubuntu"' -o ConnectTimeout=10 -o ControlPath=/home/madhead/.ansible/cp/ce66bf9464 129.213.115.167 '/bin/sh -c '"'"'chmod u+x /home/ubuntu/.ansible/tmp/ansible-tmp-1614010640.9152727-57712-172306848124621/ /home/ubuntu/.ansible/tmp/ansible-tmp-1614010640.9152727-57712-172306848124621/AnsiballZ_grafana_dashboard.py && sleep 0'"'"''                                                                                                                                          
<129.213.115.167> (0, b'', b'')
<129.213.115.167> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<129.213.115.167> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/home/madhead/.ssh/bots@oracle-cloud"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ubuntu"' -o ConnectTimeout=10 -o ControlPath=/home/madhead/.ansible/cp/ce66bf9464 -tt 129.213.115.167 '/bin/sh -c '"'"'sudo -H -S -n  -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-lpueoextieqtiwyvbrkwewlrhpygvkda ; /usr/bin/python3 /home/ubuntu/.ansible/tmp/ansible-tmp-1614010640.9152727-57712-172306848124621/AnsiballZ_grafana_dashboard.py'"'"'"'"'"'"'"'"' && sleep 0'"'"''                                                                                    
Escalation succeeded
<129.213.115.167> (1, b'\r\nTraceback (most recent call last):\r\n  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1614010640.9152727-57712-172306848124621/AnsiballZ_grafana_dashboard.py", line 102, in <module>\r\n    _ansiballz_main()\r\n  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1614010640.9152727-57712-172306848124621/AnsiballZ_grafana_dashboard.py", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1614010640.9152727-57712-172306848124621/AnsiballZ_grafana_dashboard.py", line 40, in invoke_module\r\n    runpy.run_module(mod_name=\'ansible_collections.community.grafana.plugins.modules.grafana_dashboard\', init_globals=None, run_name=\'__main__\', alter_sys=True)\r\n  File "/usr/lib/python3.8/runpy.py", line 207, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code\r\n    _run_code(code, mod_globals, init_globals,\r\n  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File "/tmp/ansible_community.grafana.grafana_dashboard_payload_69jiv_26/ansible_community.grafana.grafana_dashboard_payload.zip/ansible_collections/community/grafana/plugins/modules/grafana_dashboard.py", line 566, in <module>\r\n  File "/tmp/ansible_community.grafana.grafana_dashboard_payload_69jiv_26/ansible_community.grafana.grafana_dashboard_payload.zip/ansible_collections/community/grafana/plugins/modules/grafana_dashboard.py", line 528, in main\r\n  File "/tmp/ansible_community.grafana.grafana_dashboard_payload_69jiv_26/ansible_community.grafana.grafana_dashboard_payload.zip/ansible_collections/community/grafana/plugins/modules/grafana_dashboard.py", line 381, in grafana_create_dashboard\r\nKeyError: \'commit_message\'\r\n', b'Shared connection to 129.213.115.167 closed.\r\n')                                                                                                                                                                        
<129.213.115.167> Failed to connect to the host via ssh: Shared connection to 129.213.115.167 closed.
<129.213.115.167> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<129.213.115.167> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/home/madhead/.ssh/bots@oracle-cloud"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ubuntu"' -o ConnectTimeout=10 -o ControlPath=/home/madhead/.ansible/cp/ce66bf9464 129.213.115.167 '/bin/sh -c '"'"'rm -f -r /home/ubuntu/.ansible/tmp/ansible-tmp-1614010640.9152727-57712-172306848124621/ > /dev/null 2>&1 && sleep 0'"'"''                                           
<129.213.115.167> (0, b'', b'')
fatal: [129.213.115.167]: FAILED! => {
    "changed": false,
    "module_stderr": "Shared connection to 129.213.115.167 closed.\r\n",
    "module_stdout": "\r\nTraceback (most recent call last):\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1614010640.9152727-57712-172306848124621/AnsiballZ_grafana_dashboard.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1614010640.9152727-57712-172306848124621/AnsiballZ_grafana_dashboard.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1614010640.9152727-57712-172306848124621/AnsiballZ_grafana_dashboard.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.community.grafana.plugins.modules.grafana_dashboard', init_globals=None, run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\r\n    _run_code(code, mod_globals, init_globals,\r\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_community.grafana.grafana_dashboard_payload_69jiv_26/ansible_community.grafana.grafana_dashboard_payload.zip/ansible_collections/community/grafana/plugins/modules/grafana_dashboard.py\", line 566, in <module>\r\n  File \"/tmp/ansible_community.grafana.grafana_dashboard_payload_69jiv_26/ansible_community.grafana.grafana_dashboard_payload.zip/ansible_collections/community/grafana/plugins/modules/grafana_dashboard.py\", line 528, in main\r\n  File \"/tmp/ansible_community.grafana.grafana_dashboard_payload_69jiv_26/ansible_community.grafana.grafana_dashboard_payload.zip/ansible_collections/community/grafana/plugins/modules/grafana_dashboard.py\", line 381, in grafana_create_dashboard\r\nKeyError: 'commit_message'\r\n",                      
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by madhead** [comment]
It seems to be related to https://github.com/ansible-collections/community.grafana/issues/147, but IFAIU its fix included code changes for `grafana_folder` and `grafana_teams` whereas this issue is related to `grafana_dashboard`.

Although, the lines of code it mentions, 381, seems to be related to another issue happened, that was being reported https://github.com/ansible-collections/community.grafana/blob/e8b234eb812237d1cc85a7474d88832901c5d1f3/plugins/modules/grafana_dashboard.py#L379-L382
